# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gorges' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  # Pods for Gorges

  target 'GorgesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GorgesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
